# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Role Info

# Model Form Field configuration
form: $/kosmoskosmos/gar/models/roleinfo/fields.yaml

# Model Class name
modelClass: KosmosKosmos\GAR\Models\RoleInfo

# Default redirect location
defaultRedirect: kosmoskosmos/gar/roleinfos

# Create page
create:
    title: Create Role Info
    redirect: kosmoskosmos/gar/roleinfos/update/:id
    redirectClose: kosmoskosmos/gar/roleinfos

# Update page
update:
    title: Edit Role Info
    redirect: kosmoskosmos/gar/roleinfos
    redirectClose: kosmoskosmos/gar/roleinfos

# Preview page
preview:
    title: Preview Role Info
